name: Setup
description: Setup Java, Maven & AWS Credentials

inputs:
  aws-access-key-id:
    description: "AWS Access Key Id"
    required: true
  aws-secret-access-key:
    description: "AWS Secret Access Key"
    required: true
  aws-region:
    description: "AWS Region"
    required: true
  java-version:
    description: "JDK Version"
    required: true
  maven-version:
    description: "Apache Maven Version"
    required: true

runs:
  using: composite
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'
        cache: maven

    - name: Setup Maven ${{ inputs.maven-version }}
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: ${{ inputs.maven-version }}

#    - name: Set JFrog Basic Auth Header
#      shell: bash
#      run: |
#        echo "JFROG_AUTH_HEADER=$(echo -n '${{ inputs.JF_USER }}:${{ inputs.JF_PASSWORD }}' | base64)" >> $GITHUB_ENV
#
#    - name: Generate settings.xml with HTTP Header Auth
#      shell: bash
#      run: |
#        mkdir -p ~/.m2
#        cat > ~/.m2/settings.xml <<EOF
#        <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
#                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
#                  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
#          <servers>
#            <server>
#              <id>rkc-hosted-snapshots</id>
#              <configuration>
#                <httpHeaders>
#                  <property>
#                    <name>Authorization</name>
#                    <value>Basic ${JFROG_AUTH_HEADER}</value>
#                  </property>
#                </httpHeaders>
#              </configuration>
#            </server>
#            <server>
#              <id>rkc-hosted-releases</id>
#              <configuration>
#                <httpHeaders>
#                  <property>
#                    <name>Authorization</name>
#                    <value>Basicconfiguration>
#            </server>
#          </servers>
#        </settings>
#        EOF

    - name: Generate settings.xml for Maven Builds
      uses: whelk-io/maven-settings-xml-action@v22
      with:
        repositories: >
          [
            {
              "id": "rkc-hosted-releases",
              "name": "rkc-hosted-releases",
              "url": "https://trial9b3ps3.jfrog.io/artifactory/hosted-snapshots-libs-release",
              "releases": {
                "enabled": "true",
                "updatePolicy": "never"
              },
              "snapshots": {
                "enabled": "false"
              }
            },
            {
              "id": "rkc-hosted-snapshots",
              "name": "rkc-hosted-snapshots",
              "url": "https://trial9b3ps3.jfrog.io/artifactory/hosted-snapshots-libs-snapshot",
              "releases": {
                "enabled": "false",
                "updatePolicy": "never"
              },
              "snapshots": {
                "enabled": "true"
              }
            }
          ]
        servers: >
          [
            {
              "id": "rkc-hosted-snapshots",
              "username": "${ inputs.JF_USER }",
              "password": "${ inputs.JF_PASSWORD }"
            },
            {
              "id": "rkc-hosted-releases",
              "username": "${ inputs.JF_USER }",
              "password": "${ inputs.JF_PASSWORD }"
            }
          ]
