name: Setup
description: Setup Java, Maven & AWS Credentials

inputs:
  aws-access-key-id:
    description: "AWS Access Key Id"
    required: true
  aws-secret-access-key:
    description: "AWS Secret Access Key"
    required: true
  aws-region:
    description: "AWS Region"
    required: true
  java-version:
    description: "JDK Version"
    required: true
  maven-version:
    description: "Apache Maven Version"
    required: true

runs:
  using: composite
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'
        cache: maven

    - name: Setup Maven ${{ inputs.maven-version }}
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: ${{ inputs.maven-version }}

    - name: Connect to Jfrog artifactory
      uses: jfrog/setup-jfrog-cli@v4
      env:
        # JFrog Platform url
        JF_URL: ${{ vars.JF_URL }} # or 'https://acme.jfrog.io'

        # Basic authentication credentials
        JF_USER: ${{ secrets.JF_USER }}
        JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
        # or
        # JFrog Platform access token
#        JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
    - run: |
          jf rt ping
        echo "AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID" >> $GITHUB_ENV

    - name: Generate settings.xml for Maven Builds
      uses: whelk-io/maven-settings-xml-action@v22
      with:
        repositories: >
          [
            {
              "id": "rkc-hosted-releases",
              "name": "rkc-hosted-releases",
              "url": "https://trial9b3ps3.jfrog.io/artifactory/hosted-snapshots-libs-release",
              "releases": {
                "enabled": "true",
                "updatePolicy": "never"
              },
              "snapshots": {
                "enabled": "false"
              }
            },
            {
              "id": "rkc-hosted-snapshots",
              "name": "rkc-hosted-snapshots",
              "url": "https://trial9b3ps3.jfrog.io/artifactory/hosted-snapshots-libs-snapshot",
              "releases": {
                "enabled": "false",
                "updatePolicy": "never"
              },
              "snapshots": {
                "enabled": "true"
              }
            }
          ]
        servers: >
          [
            {
              "id": "rkc-hosted-snapshots",
              "username": "aws",
              "password": "${env.CODEARTIFACT_AUTH_TOKEN}"
            },
            {
              "id": "rkc-hosted-releases",
              "username": "aws",
              "password": "${env.CODEARTIFACT_AUTH_TOKEN}"
            }
          ]
