name: Setup
description: Setup Java, Maven & AWS Credentials

inputs:
  aws-access-key-id:
    description: "AWS Access Key Id"
    required: true
  aws-secret-access-key:
    description: "AWS Secret Access Key"
    required: true
  aws-region:
    description: "AWS Region"
    required: true
  java-version:
    description: "JDK Version"
    required: true
  maven-version:
    description: "Apache Maven Version"
    required: true

runs:
  using: composite
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'
        cache: maven

    - name: Setup Maven ${{ inputs.maven-version }}
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: ${{ inputs.maven-version }}

    - name: Generate settings.xml for Maven Builds
      uses: whelk-io/maven-settings-xml-action@v22
      with:
        repositories: >
          [
            {
              "id": "rkc-hosted-releases",
              "name": "rkc-hosted-releases",
              "url": "https://trial9b3ps3.jfrog.io/artifactory/hosted-snapshots-libs-release",
              "releases": {
                "enabled": "true",
                "updatePolicy": "never"
              },
              "snapshots": {
                "enabled": "false"
              }
            },
            {
              "id": "rkc-hosted-snapshots",
              "name": "rkc-hosted-snapshots",
              "url": "https://trial9b3ps3.jfrog.io/artifactory/hosted-snapshots-libs-snapshot",
              "releases": {
                "enabled": "false",
                "updatePolicy": "never"
              },
              "snapshots": {
                "enabled": "true"
              }
            }
          ]
        servers: >
          [
            {
              "id": "rkc-hosted-snapshots",
              "username": "${ inputs.JF_USER }",
              "password": "${ inputs.JS_PASSWORD }"
            },
            {
              "id": "rkc-hosted-releases",
              "username": "${ inputs.JF_USER }",
              "password": "${ inputs.JS_PASSWORD }"
            }
          ]
